# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: iata-case-study-using-sls

# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

# plugins:
#   - serverless-python-requirements

custom:
  log_level: 'INFO'
  bucket_name: "s3-sls-walid-iata-case-study"
  zip_path: 'ZIP/'
  raw_path: 'RAW/'
  cleaned_path: 'CLEANED/'
  lambda_prefix: "lambda-sls-iata-cs"
  role_prefix: "role-sls-iata-cs"
  policy_prefix: "policy-sls-iata-cs"
  pythonRequirements:
    pythonBin: python3

package:
  individually: true

provider:
  name: aws
  region: eu-central-1
  runtime: python3.11
  deploymentBucket:
    name: s3-iata-case-study-deployment-bucket
    serverSideEncryption: aws:kms

functions:
  data-ingestion:
    handler: data_ingestion.handler.lambda_handler
    package:
      artifact: lambdas/lambdas.zip
    name: ${self:custom.lambda_prefix}-data-ingestion
    role: lambdaRole
    timeout: 300
    # memorySize: 2048
    layers:
      - arn:aws:lambda:eu-central-1:336392948345:layer:AWSSDKPandas-Python311:2
    environment:
      BUCKET_NAME: ${self:custom.bucket_name}
      ZIP_PATH: ${self:custom.zip_path}
      RAW_PATH: ${self:custom.raw_path}
      CLEANED_PATH: ${self:custom.cleaned_path}
      LOG_LEVEL: ${self:custom.log_level}

  data-extraction:
    handler: data_extraction.handler.lambda_handler
    package:
      artifact: lambdas/lambdas.zip
    name: ${self:custom.lambda_prefix}-data-extraction
    role: lambdaRole
    timeout: 300
    # memorySize: 2048
    layers:
      - arn:aws:lambda:eu-central-1:336392948345:layer:AWSSDKPandas-Python311:2
    environment:
      BUCKET_NAME: ${self:custom.bucket_name}
      ZIP_PATH: ${self:custom.zip_path}
      RAW_PATH: ${self:custom.raw_path}
      CLEANED_PATH: ${self:custom.cleaned_path}
      LOG_LEVEL: ${self:custom.log_level}
    events:
      - s3:
          bucket: ${self:custom.bucket_name}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${self:custom.zip_path}
            - suffix: .zip
          existing: true


resources:
  - ${file(s3-bucket.yml)}
  - ${file(iam.yml)}