# This is a basic workflow to help you get started with Actions
name: Deploy with CDF

env:
  deploymentBucket: 's3-iata-case-study-deployment-bucket'
  lambdaZipPath: 'package/lambdas.zip'

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  



  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: AWS creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: create and upload lambda package
        run: |
          cd lambdas
          zip -ur lambdas.zip .
          aws s3 cp lambdas.zip s3://$deploymentBucket/$lambdaZipPath
      
      - name: upload ETL scripts
        run: |
          aws s3 cp ETL s3://$deploymentBucket/ETL --recursive
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo lambdaZipPath=$lambdaZipPath,deploymentBucket=$deploymentBucket

      - name: AWS creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: deploy
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        # env:
        #   deploymentBucket = ${deploymentBucket}
        #   lambdaZipPath=${lambdaZipPath}
        with:
          name: iata-case-study-using-cdf
          capabilities: CAPABILITY_NAMED_IAM
          template: iata-case-study-using-cdf.yaml
          parameter-overrides: "lambdaZipPath=${{env.lambdaZipPath}},deploymentBucket=${{env.deploymentBucket}}"